steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'navalplan-researcher'          # Service Name
  - '--source'
  - '.'
  - '--region'
  - 'us-central1'
  - '--project'
  - '${PROJECT_ID}'                   # Your Google Cloud Project ID
  - '--no-allow-unauthenticated'    # Security: Only backend can call this
  - '--set-secrets=NAVALPLAN_BACKEND_MAPS_API_KEY=NAVALPLAN_BACKEND_MAPS_API_KEY:latest'
  - '--set-secrets=GEMINI_API_KEY=NAVALPLAN_GEMINI_KEY:latest'
  - '--set-secrets=NAVALPLAN_TIDAL_UKTIDAL_API_KEY=NAVALPLAN_TIDAL_UKTIDAL_API_KEY:latest'
  - '--set-secrets=NAVALPLAN_TIDAL_NIWA_API_KEY=NAVALPLAN_TIDAL_NIWA_API_KEY:latest'
  - '--set-env-vars=NAVALPLAN_AGENT_MODEL=${_NAVALPLAN_AGENT_MODEL}'
  - '--set-env-vars=ENV=${_ENV}'
  dir: 'code/services/researcher'        # Build context
substitutions:
  _NAVALPLAN_AGENT_MODEL: "gemini-2.5-flash"
  _ENV: "production"
logsBucket: gs://navalplan-logging-bucket
